#include <stdio.h>
#include "basext.h"
#include "japi_p.h"


/*

   generated by makejapi4scriba   DO NOT EDIT

      Wed May 22 20:27:49 2013
 

 */


besVERSION_NEGOTIATE
    return (int)INTERFACE_VERSION;
besEND

besSUB_START
besEND

besSUB_FINISH
besEND

besFUNCTION (__j_scriba_start)

    if(besARGNR<0) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>0) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_start();

besEND

besFUNCTION (__j_scriba_connect)
    VARIABLE ptr;
    char* arg0;

    if(besARGNR<1) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>1) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = besCONVERT2ZCHAR(besCONVERT2STRING(ptr),arg0);

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_connect(arg0);

    besFREE(arg0);
besEND

besFUNCTION (__j_scriba_setport)
    VARIABLE ptr;
    int   arg0;

    if(besARGNR<1) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>1) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_setport(arg0);

besEND

besFUNCTION (__j_scriba_setdebug)
    VARIABLE ptr;
    int   arg0;

    if(besARGNR<1) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>1) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_setdebug(arg0);

besEND

besFUNCTION (__j_scriba_frame)
    VARIABLE ptr;
    char* arg0;

    if(besARGNR<1) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>1) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = besCONVERT2ZCHAR(besCONVERT2STRING(ptr),arg0);

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_frame(arg0);

    besFREE(arg0);
besEND

besFUNCTION (__j_scriba_button)
    VARIABLE ptr;
    int   arg0;
    char* arg1;

    if(besARGNR<2) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>2) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = besCONVERT2ZCHAR(besCONVERT2STRING(ptr),arg1);

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_button(arg0,arg1);

    besFREE(arg1);
besEND

besFUNCTION (__j_scriba_graphicbutton)
    VARIABLE ptr;
    int   arg0;
    char* arg1;

    if(besARGNR<2) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>2) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = besCONVERT2ZCHAR(besCONVERT2STRING(ptr),arg1);

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_graphicbutton(arg0,arg1);

    besFREE(arg1);
besEND

besFUNCTION (__j_scriba_checkbox)
    VARIABLE ptr;
    int   arg0;
    char* arg1;

    if(besARGNR<2) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>2) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = besCONVERT2ZCHAR(besCONVERT2STRING(ptr),arg1);

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_checkbox(arg0,arg1);

    besFREE(arg1);
besEND

besFUNCTION (__j_scriba_label)
    VARIABLE ptr;
    int   arg0;
    char* arg1;

    if(besARGNR<2) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>2) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = besCONVERT2ZCHAR(besCONVERT2STRING(ptr),arg1);

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_label(arg0,arg1);

    besFREE(arg1);
besEND

besFUNCTION (__j_scriba_graphiclabel)
    VARIABLE ptr;
    int   arg0;
    char* arg1;

    if(besARGNR<2) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>2) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = besCONVERT2ZCHAR(besCONVERT2STRING(ptr),arg1);

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_graphiclabel(arg0,arg1);

    besFREE(arg1);
besEND

besFUNCTION (__j_scriba_canvas)
    VARIABLE ptr;
    int   arg0;
    int   arg1;
    int   arg2;

    if(besARGNR<3) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>3) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(3);
    besDEREFERENCE(ptr);
    arg2 = LONGVALUE(besCONVERT2LONG(ptr));

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_canvas(arg0,arg1,arg2);

besEND

besFUNCTION (__j_scriba_panel)
    VARIABLE ptr;
    int   arg0;

    if(besARGNR<1) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>1) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_panel(arg0);

besEND

besFUNCTION (__j_scriba_borderpanel)
    VARIABLE ptr;
    int   arg0;
    int   arg1;

    if(besARGNR<2) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>2) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_borderpanel(arg0,arg1);

besEND

besFUNCTION (__j_scriba_radiogroup)
    VARIABLE ptr;
    int   arg0;

    if(besARGNR<1) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>1) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_radiogroup(arg0);

besEND

besFUNCTION (__j_scriba_radiobutton)
    VARIABLE ptr;
    int   arg0;
    char* arg1;

    if(besARGNR<2) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>2) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = besCONVERT2ZCHAR(besCONVERT2STRING(ptr),arg1);

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_radiobutton(arg0,arg1);

    besFREE(arg1);
besEND

besFUNCTION (__j_scriba_list)
    VARIABLE ptr;
    int   arg0;
    int   arg1;

    if(besARGNR<2) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>2) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_list(arg0,arg1);

besEND

besFUNCTION (__j_scriba_choice)
    VARIABLE ptr;
    int   arg0;

    if(besARGNR<1) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>1) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_choice(arg0);

besEND

besFUNCTION (__j_scriba_dialog)
    VARIABLE ptr;
    int   arg0;
    char* arg1;

    if(besARGNR<2) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>2) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = besCONVERT2ZCHAR(besCONVERT2STRING(ptr),arg1);

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_dialog(arg0,arg1);

    besFREE(arg1);
besEND

besFUNCTION (__j_scriba_window)
    VARIABLE ptr;
    int   arg0;

    if(besARGNR<1) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>1) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_window(arg0);

besEND

besFUNCTION (__j_scriba_popupmenu)
    VARIABLE ptr;
    int   arg0;
    char* arg1;

    if(besARGNR<2) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>2) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = besCONVERT2ZCHAR(besCONVERT2STRING(ptr),arg1);

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_popupmenu(arg0,arg1);

    besFREE(arg1);
besEND

besFUNCTION (__j_scriba_scrollpane)
    VARIABLE ptr;
    int   arg0;

    if(besARGNR<1) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>1) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_scrollpane(arg0);

besEND

besFUNCTION (__j_scriba_hscrollbar)
    VARIABLE ptr;
    int   arg0;

    if(besARGNR<1) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>1) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_hscrollbar(arg0);

besEND

besFUNCTION (__j_scriba_vscrollbar)
    VARIABLE ptr;
    int   arg0;

    if(besARGNR<1) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>1) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_vscrollbar(arg0);

besEND

besFUNCTION (__j_scriba_line)
    VARIABLE ptr;
    int   arg0;
    int   arg1;
    int   arg2;
    int   arg3;

    if(besARGNR<4) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>4) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(3);
    besDEREFERENCE(ptr);
    arg2 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(4);
    besDEREFERENCE(ptr);
    arg3 = LONGVALUE(besCONVERT2LONG(ptr));

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_line(arg0,arg1,arg2,arg3);

besEND

besFUNCTION (__j_scriba_printer)
    VARIABLE ptr;
    int   arg0;

    if(besARGNR<1) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>1) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_printer(arg0);

besEND

besFUNCTION (__j_scriba_image)
    VARIABLE ptr;
    int   arg0;
    int   arg1;

    if(besARGNR<2) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>2) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_image(arg0,arg1);

besEND

besFUNCTION (__j_scriba_filedialog)
    VARIABLE ptr;
    int   arg0;
    char* arg1;
    char* arg2;
    char* retstr;

    if(besARGNR<4) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>4) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = besCONVERT2ZCHAR(besCONVERT2STRING(ptr),arg1);

    ptr = besARGUMENT(3);
    besDEREFERENCE(ptr);
    arg2 = besCONVERT2ZCHAR(besCONVERT2STRING(ptr),arg2);


    retstr=japi_filedialog(arg0,arg1,arg2,NULL);

    besALLOC_RETURN_STRING(strlen(retstr));
    memcpy(STRINGVALUE(besRETURNVALUE),retstr,strlen(retstr));
    besFREE(arg1);
    besFREE(arg2);
besEND

besFUNCTION (__j_scriba_fileselect)
    VARIABLE ptr;
    int   arg0;
    char* arg1;
    char* arg2;
    char* retstr;

    if(besARGNR<4) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>4) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = besCONVERT2ZCHAR(besCONVERT2STRING(ptr),arg1);

    ptr = besARGUMENT(3);
    besDEREFERENCE(ptr);
    arg2 = besCONVERT2ZCHAR(besCONVERT2STRING(ptr),arg2);


    retstr=japi_fileselect(arg0,arg1,arg2,NULL);

    besALLOC_RETURN_STRING(strlen(retstr));
    memcpy(STRINGVALUE(besRETURNVALUE),retstr,strlen(retstr));
    besFREE(arg1);
    besFREE(arg2);
besEND

besFUNCTION (__j_scriba_messagebox)
    VARIABLE ptr;
    int   arg0;
    char* arg1;
    char* arg2;

    if(besARGNR<3) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>3) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = besCONVERT2ZCHAR(besCONVERT2STRING(ptr),arg1);

    ptr = besARGUMENT(3);
    besDEREFERENCE(ptr);
    arg2 = besCONVERT2ZCHAR(besCONVERT2STRING(ptr),arg2);

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_messagebox(arg0,arg1,arg2);

    besFREE(arg1);
    besFREE(arg2);
besEND

besFUNCTION (__j_scriba_alertbox)
    VARIABLE ptr;
    int   arg0;
    char* arg1;
    char* arg2;
    char* arg3;

    if(besARGNR<4) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>4) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = besCONVERT2ZCHAR(besCONVERT2STRING(ptr),arg1);

    ptr = besARGUMENT(3);
    besDEREFERENCE(ptr);
    arg2 = besCONVERT2ZCHAR(besCONVERT2STRING(ptr),arg2);

    ptr = besARGUMENT(4);
    besDEREFERENCE(ptr);
    arg3 = besCONVERT2ZCHAR(besCONVERT2STRING(ptr),arg3);

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_alertbox(arg0,arg1,arg2,arg3);

    besFREE(arg1);
    besFREE(arg2);
    besFREE(arg3);
besEND

besFUNCTION (__j_scriba_choicebox2)
    VARIABLE ptr;
    int   arg0;
    char* arg1;
    char* arg2;
    char* arg3;
    char* arg4;

    if(besARGNR<5) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>5) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = besCONVERT2ZCHAR(besCONVERT2STRING(ptr),arg1);

    ptr = besARGUMENT(3);
    besDEREFERENCE(ptr);
    arg2 = besCONVERT2ZCHAR(besCONVERT2STRING(ptr),arg2);

    ptr = besARGUMENT(4);
    besDEREFERENCE(ptr);
    arg3 = besCONVERT2ZCHAR(besCONVERT2STRING(ptr),arg3);

    ptr = besARGUMENT(5);
    besDEREFERENCE(ptr);
    arg4 = besCONVERT2ZCHAR(besCONVERT2STRING(ptr),arg4);

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_choicebox2(arg0,arg1,arg2,arg3,arg4);

    besFREE(arg1);
    besFREE(arg2);
    besFREE(arg3);
    besFREE(arg4);
besEND

besFUNCTION (__j_scriba_choicebox3)
    VARIABLE ptr;
    int   arg0;
    char* arg1;
    char* arg2;
    char* arg3;
    char* arg4;
    char* arg5;

    if(besARGNR<6) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>6) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = besCONVERT2ZCHAR(besCONVERT2STRING(ptr),arg1);

    ptr = besARGUMENT(3);
    besDEREFERENCE(ptr);
    arg2 = besCONVERT2ZCHAR(besCONVERT2STRING(ptr),arg2);

    ptr = besARGUMENT(4);
    besDEREFERENCE(ptr);
    arg3 = besCONVERT2ZCHAR(besCONVERT2STRING(ptr),arg3);

    ptr = besARGUMENT(5);
    besDEREFERENCE(ptr);
    arg4 = besCONVERT2ZCHAR(besCONVERT2STRING(ptr),arg4);

    ptr = besARGUMENT(6);
    besDEREFERENCE(ptr);
    arg5 = besCONVERT2ZCHAR(besCONVERT2STRING(ptr),arg5);

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_choicebox3(arg0,arg1,arg2,arg3,arg4,arg5);

    besFREE(arg1);
    besFREE(arg2);
    besFREE(arg3);
    besFREE(arg4);
    besFREE(arg5);
besEND

besFUNCTION (__j_scriba_progressbar)
    VARIABLE ptr;
    int   arg0;
    int   arg1;

    if(besARGNR<2) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>2) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_progressbar(arg0,arg1);

besEND

besFUNCTION (__j_scriba_led)
    VARIABLE ptr;
    int   arg0;
    int   arg1;
    int   arg2;

    if(besARGNR<3) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>3) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(3);
    besDEREFERENCE(ptr);
    arg2 = LONGVALUE(besCONVERT2LONG(ptr));

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_led(arg0,arg1,arg2);

besEND

besFUNCTION (__j_scriba_sevensegment)
    VARIABLE ptr;
    int   arg0;
    int   arg1;

    if(besARGNR<2) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>2) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_sevensegment(arg0,arg1);

besEND

besFUNCTION (__j_scriba_meter)
    VARIABLE ptr;
    int   arg0;
    char* arg1;

    if(besARGNR<2) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>2) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = besCONVERT2ZCHAR(besCONVERT2STRING(ptr),arg1);

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_meter(arg0,arg1);

    besFREE(arg1);
besEND

besFUNCTION (__j_scriba_additem)
    VARIABLE ptr;
    int   arg0;
    char* arg1;

    if(besARGNR<2) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>2) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = besCONVERT2ZCHAR(besCONVERT2STRING(ptr),arg1);

    besRETURNVALUE = NULL;
    japi_additem(arg0,arg1);

    besFREE(arg1);
besEND

besFUNCTION (__j_scriba_textfield)
    VARIABLE ptr;
    int   arg0;
    int   arg1;

    if(besARGNR<2) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>2) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_textfield(arg0,arg1);

besEND

besFUNCTION (__j_scriba_textarea)
    VARIABLE ptr;
    int   arg0;
    int   arg1;
    int   arg2;

    if(besARGNR<3) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>3) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(3);
    besDEREFERENCE(ptr);
    arg2 = LONGVALUE(besCONVERT2LONG(ptr));

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_textarea(arg0,arg1,arg2);

besEND

besFUNCTION (__j_scriba_menubar)
    VARIABLE ptr;
    int   arg0;

    if(besARGNR<1) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>1) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_menubar(arg0);

besEND

besFUNCTION (__j_scriba_menu)
    VARIABLE ptr;
    int   arg0;
    char* arg1;

    if(besARGNR<2) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>2) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = besCONVERT2ZCHAR(besCONVERT2STRING(ptr),arg1);

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_menu(arg0,arg1);

    besFREE(arg1);
besEND

besFUNCTION (__j_scriba_helpmenu)
    VARIABLE ptr;
    int   arg0;
    char* arg1;

    if(besARGNR<2) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>2) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = besCONVERT2ZCHAR(besCONVERT2STRING(ptr),arg1);

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_helpmenu(arg0,arg1);

    besFREE(arg1);
besEND

besFUNCTION (__j_scriba_menuitem)
    VARIABLE ptr;
    int   arg0;
    char* arg1;

    if(besARGNR<2) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>2) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = besCONVERT2ZCHAR(besCONVERT2STRING(ptr),arg1);

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_menuitem(arg0,arg1);

    besFREE(arg1);
besEND

besFUNCTION (__j_scriba_checkmenuitem)
    VARIABLE ptr;
    int   arg0;
    char* arg1;

    if(besARGNR<2) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>2) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = besCONVERT2ZCHAR(besCONVERT2STRING(ptr),arg1);

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_checkmenuitem(arg0,arg1);

    besFREE(arg1);
besEND

besFUNCTION (__j_scriba_pack)
    VARIABLE ptr;
    int   arg0;

    if(besARGNR<1) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>1) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_pack(arg0);

besEND

besFUNCTION (__j_scriba_print)
    VARIABLE ptr;
    int   arg0;

    if(besARGNR<1) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>1) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_print(arg0);

besEND

besFUNCTION (__j_scriba_playsoundfile)
    VARIABLE ptr;
    char* arg0;

    if(besARGNR<1) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>1) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = besCONVERT2ZCHAR(besCONVERT2STRING(ptr),arg0);

    besRETURNVALUE = NULL;
    japi_playsoundfile(arg0);

    besFREE(arg0);
besEND

besFUNCTION (__j_scriba_play)
    VARIABLE ptr;
    int   arg0;

    if(besARGNR<1) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>1) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_play(arg0);

besEND

besFUNCTION (__j_scriba_sound)
    VARIABLE ptr;
    char* arg0;

    if(besARGNR<1) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>1) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = besCONVERT2ZCHAR(besCONVERT2STRING(ptr),arg0);

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_sound(arg0);

    besFREE(arg0);
besEND

besFUNCTION (__j_scriba_setfont)
    VARIABLE ptr;
    int   arg0;
    int   arg1;
    int   arg2;
    int   arg3;

    if(besARGNR<4) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>4) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(3);
    besDEREFERENCE(ptr);
    arg2 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(4);
    besDEREFERENCE(ptr);
    arg3 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_setfont(arg0,arg1,arg2,arg3);

besEND

besFUNCTION (__j_scriba_setfontname)
    VARIABLE ptr;
    int   arg0;
    int   arg1;

    if(besARGNR<2) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>2) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_setfontname(arg0,arg1);

besEND

besFUNCTION (__j_scriba_setfontsize)
    VARIABLE ptr;
    int   arg0;
    int   arg1;

    if(besARGNR<2) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>2) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_setfontsize(arg0,arg1);

besEND

besFUNCTION (__j_scriba_setfontstyle)
    VARIABLE ptr;
    int   arg0;
    int   arg1;

    if(besARGNR<2) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>2) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_setfontstyle(arg0,arg1);

besEND

besFUNCTION (__j_scriba_seperator)
    VARIABLE ptr;
    int   arg0;

    if(besARGNR<1) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>1) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_seperator(arg0);

besEND

besFUNCTION (__j_scriba_disable)
    VARIABLE ptr;
    int   arg0;

    if(besARGNR<1) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>1) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_disable(arg0);

besEND

besFUNCTION (__j_scriba_enable)
    VARIABLE ptr;
    int   arg0;

    if(besARGNR<1) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>1) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_enable(arg0);

besEND

besFUNCTION (__j_scriba_getstate)
    VARIABLE ptr;
    int   arg0;

    if(besARGNR<1) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>1) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_getstate(arg0);

besEND

besFUNCTION (__j_scriba_getrows)
    VARIABLE ptr;
    int   arg0;

    if(besARGNR<1) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>1) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_getrows(arg0);

besEND

besFUNCTION (__j_scriba_getcolumns)
    VARIABLE ptr;
    int   arg0;

    if(besARGNR<1) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>1) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_getcolumns(arg0);

besEND

besFUNCTION (__j_scriba_getselect)
    VARIABLE ptr;
    int   arg0;

    if(besARGNR<1) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>1) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_getselect(arg0);

besEND

besFUNCTION (__j_scriba_isselect)
    VARIABLE ptr;
    int   arg0;
    int   arg1;

    if(besARGNR<2) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>2) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_isselect(arg0,arg1);

besEND

besFUNCTION (__j_scriba_isvisible)
    VARIABLE ptr;
    int   arg0;

    if(besARGNR<1) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>1) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_isvisible(arg0);

besEND

besFUNCTION (__j_scriba_isparent)
    VARIABLE ptr;
    int   arg0;
    int   arg1;

    if(besARGNR<2) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>2) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_isparent(arg0,arg1);

besEND

besFUNCTION (__j_scriba_isresizable)
    VARIABLE ptr;
    int   arg0;

    if(besARGNR<1) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>1) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_isresizable(arg0);

besEND

besFUNCTION (__j_scriba_select)
    VARIABLE ptr;
    int   arg0;
    int   arg1;

    if(besARGNR<2) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>2) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_select(arg0,arg1);

besEND

besFUNCTION (__j_scriba_deselect)
    VARIABLE ptr;
    int   arg0;
    int   arg1;

    if(besARGNR<2) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>2) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_deselect(arg0,arg1);

besEND

besFUNCTION (__j_scriba_multiplemode)
    VARIABLE ptr;
    int   arg0;
    int   arg1;

    if(besARGNR<2) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>2) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_multiplemode(arg0,arg1);

besEND

besFUNCTION (__j_scriba_insert)
    VARIABLE ptr;
    int   arg0;
    int   arg1;
    char* arg2;

    if(besARGNR<3) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>3) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(3);
    besDEREFERENCE(ptr);
    arg2 = besCONVERT2ZCHAR(besCONVERT2STRING(ptr),arg2);

    besRETURNVALUE = NULL;
    japi_insert(arg0,arg1,arg2);

    besFREE(arg2);
besEND

besFUNCTION (__j_scriba_remove)
    VARIABLE ptr;
    int   arg0;
    int   arg1;

    if(besARGNR<2) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>2) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_remove(arg0,arg1);

besEND

besFUNCTION (__j_scriba_removeitem)
    VARIABLE ptr;
    int   arg0;
    char* arg1;

    if(besARGNR<2) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>2) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = besCONVERT2ZCHAR(besCONVERT2STRING(ptr),arg1);

    besRETURNVALUE = NULL;
    japi_removeitem(arg0,arg1);

    besFREE(arg1);
besEND

besFUNCTION (__j_scriba_removeall)
    VARIABLE ptr;
    int   arg0;

    if(besARGNR<1) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>1) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_removeall(arg0);

besEND

besFUNCTION (__j_scriba_setstate)
    VARIABLE ptr;
    int   arg0;
    int   arg1;

    if(besARGNR<2) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>2) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_setstate(arg0,arg1);

besEND

besFUNCTION (__j_scriba_setrows)
    VARIABLE ptr;
    int   arg0;
    int   arg1;

    if(besARGNR<2) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>2) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_setrows(arg0,arg1);

besEND

besFUNCTION (__j_scriba_setcolumns)
    VARIABLE ptr;
    int   arg0;
    int   arg1;

    if(besARGNR<2) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>2) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_setcolumns(arg0,arg1);

besEND

besFUNCTION (__j_scriba_seticon)
    VARIABLE ptr;
    int   arg0;
    int   arg1;

    if(besARGNR<2) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>2) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_seticon(arg0,arg1);

besEND

besFUNCTION (__j_scriba_setimage)
    VARIABLE ptr;
    int   arg0;
    int   arg1;

    if(besARGNR<2) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>2) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_setimage(arg0,arg1);

besEND

besFUNCTION (__j_scriba_setvalue)
    VARIABLE ptr;
    int   arg0;
    int   arg1;

    if(besARGNR<2) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>2) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_setvalue(arg0,arg1);

besEND

besFUNCTION (__j_scriba_setradiogroup)
    VARIABLE ptr;
    int   arg0;
    int   arg1;

    if(besARGNR<2) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>2) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_setradiogroup(arg0,arg1);

besEND

besFUNCTION (__j_scriba_setunitinc)
    VARIABLE ptr;
    int   arg0;
    int   arg1;

    if(besARGNR<2) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>2) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_setunitinc(arg0,arg1);

besEND

besFUNCTION (__j_scriba_setblockinc)
    VARIABLE ptr;
    int   arg0;
    int   arg1;

    if(besARGNR<2) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>2) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_setblockinc(arg0,arg1);

besEND

besFUNCTION (__j_scriba_setmin)
    VARIABLE ptr;
    int   arg0;
    int   arg1;

    if(besARGNR<2) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>2) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_setmin(arg0,arg1);

besEND

besFUNCTION (__j_scriba_setmax)
    VARIABLE ptr;
    int   arg0;
    int   arg1;

    if(besARGNR<2) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>2) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_setmax(arg0,arg1);

besEND

besFUNCTION (__j_scriba_setdanger)
    VARIABLE ptr;
    int   arg0;
    int   arg1;

    if(besARGNR<2) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>2) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_setdanger(arg0,arg1);

besEND

besFUNCTION (__j_scriba_setslidesize)
    VARIABLE ptr;
    int   arg0;
    int   arg1;

    if(besARGNR<2) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>2) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_setslidesize(arg0,arg1);

besEND

besFUNCTION (__j_scriba_setcursor)
    VARIABLE ptr;
    int   arg0;
    int   arg1;

    if(besARGNR<2) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>2) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_setcursor(arg0,arg1);

besEND

besFUNCTION (__j_scriba_setresizable)
    VARIABLE ptr;
    int   arg0;
    int   arg1;

    if(besARGNR<2) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>2) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_setresizable(arg0,arg1);

besEND

besFUNCTION (__j_scriba_getlength)
    VARIABLE ptr;
    int   arg0;

    if(besARGNR<1) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>1) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_getlength(arg0);

besEND

besFUNCTION (__j_scriba_getvalue)
    VARIABLE ptr;
    int   arg0;

    if(besARGNR<1) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>1) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_getvalue(arg0);

besEND

besFUNCTION (__j_scriba_getdanger)
    VARIABLE ptr;
    int   arg0;

    if(besARGNR<1) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>1) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_getdanger(arg0);

besEND

besFUNCTION (__j_scriba_getscreenheight)

    if(besARGNR<0) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>0) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_getscreenheight();

besEND

besFUNCTION (__j_scriba_getscreenwidth)

    if(besARGNR<0) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>0) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_getscreenwidth();

besEND

besFUNCTION (__j_scriba_getheight)
    VARIABLE ptr;
    int   arg0;

    if(besARGNR<1) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>1) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_getheight(arg0);

besEND

besFUNCTION (__j_scriba_getwidth)
    VARIABLE ptr;
    int   arg0;

    if(besARGNR<1) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>1) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_getwidth(arg0);

besEND

besFUNCTION (__j_scriba_getinsets)
    VARIABLE ptr;
    int   arg0;
    int   arg1;

    if(besARGNR<2) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>2) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_getinsets(arg0,arg1);

besEND

besFUNCTION (__j_scriba_getlayoutid)
    VARIABLE ptr;
    int   arg0;

    if(besARGNR<1) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>1) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_getlayoutid(arg0);

besEND

besFUNCTION (__j_scriba_getinheight)
    VARIABLE ptr;
    int   arg0;

    if(besARGNR<1) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>1) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_getinheight(arg0);

besEND

besFUNCTION (__j_scriba_getinwidth)
    VARIABLE ptr;
    int   arg0;

    if(besARGNR<1) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>1) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_getinwidth(arg0);

besEND

besFUNCTION (__j_scriba_gettext)
    VARIABLE ptr;
    int   arg0;
    char* retstr;

    if(besARGNR<2) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>2) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));


    retstr=japi_gettext(arg0,NULL);

    besALLOC_RETURN_STRING(strlen(retstr));
    memcpy(STRINGVALUE(besRETURNVALUE),retstr,strlen(retstr));
besEND

besFUNCTION (__j_scriba_getitem)
    VARIABLE ptr;
    int   arg0;
    int   arg1;
    char* retstr;

    if(besARGNR<3) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>3) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));


    retstr=japi_getitem(arg0,arg1,NULL);

    besALLOC_RETURN_STRING(strlen(retstr));
    memcpy(STRINGVALUE(besRETURNVALUE),retstr,strlen(retstr));
besEND

besFUNCTION (__j_scriba_getitemcount)
    VARIABLE ptr;
    int   arg0;

    if(besARGNR<1) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>1) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_getitemcount(arg0);

besEND

besFUNCTION (__j_scriba_delete)
    VARIABLE ptr;
    int   arg0;
    int   arg1;
    int   arg2;

    if(besARGNR<3) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>3) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(3);
    besDEREFERENCE(ptr);
    arg2 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_delete(arg0,arg1,arg2);

besEND

besFUNCTION (__j_scriba_replacetext)
    VARIABLE ptr;
    int   arg0;
    char* arg1;
    int   arg2;
    int   arg3;

    if(besARGNR<4) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>4) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = besCONVERT2ZCHAR(besCONVERT2STRING(ptr),arg1);

    ptr = besARGUMENT(3);
    besDEREFERENCE(ptr);
    arg2 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(4);
    besDEREFERENCE(ptr);
    arg3 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_replacetext(arg0,arg1,arg2,arg3);

    besFREE(arg1);
besEND

besFUNCTION (__j_scriba_appendtext)
    VARIABLE ptr;
    int   arg0;
    char* arg1;

    if(besARGNR<2) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>2) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = besCONVERT2ZCHAR(besCONVERT2STRING(ptr),arg1);

    besRETURNVALUE = NULL;
    japi_appendtext(arg0,arg1);

    besFREE(arg1);
besEND

besFUNCTION (__j_scriba_inserttext)
    VARIABLE ptr;
    int   arg0;
    char* arg1;
    int   arg2;

    if(besARGNR<3) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>3) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = besCONVERT2ZCHAR(besCONVERT2STRING(ptr),arg1);

    ptr = besARGUMENT(3);
    besDEREFERENCE(ptr);
    arg2 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_inserttext(arg0,arg1,arg2);

    besFREE(arg1);
besEND

besFUNCTION (__j_scriba_settext)
    VARIABLE ptr;
    int   arg0;
    char* arg1;

    if(besARGNR<2) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>2) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = besCONVERT2ZCHAR(besCONVERT2STRING(ptr),arg1);

    besRETURNVALUE = NULL;
    japi_settext(arg0,arg1);

    besFREE(arg1);
besEND

besFUNCTION (__j_scriba_selectall)
    VARIABLE ptr;
    int   arg0;

    if(besARGNR<1) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>1) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_selectall(arg0);

besEND

besFUNCTION (__j_scriba_selecttext)
    VARIABLE ptr;
    int   arg0;
    int   arg1;
    int   arg2;

    if(besARGNR<3) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>3) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(3);
    besDEREFERENCE(ptr);
    arg2 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_selecttext(arg0,arg1,arg2);

besEND

besFUNCTION (__j_scriba_getselstart)
    VARIABLE ptr;
    int   arg0;

    if(besARGNR<1) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>1) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_getselstart(arg0);

besEND

besFUNCTION (__j_scriba_getselend)
    VARIABLE ptr;
    int   arg0;

    if(besARGNR<1) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>1) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_getselend(arg0);

besEND

besFUNCTION (__j_scriba_getseltext)
    VARIABLE ptr;
    int   arg0;
    char* retstr;

    if(besARGNR<2) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>2) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));


    retstr=japi_getseltext(arg0,NULL);

    besALLOC_RETURN_STRING(strlen(retstr));
    memcpy(STRINGVALUE(besRETURNVALUE),retstr,strlen(retstr));
besEND

besFUNCTION (__j_scriba_getcurpos)
    VARIABLE ptr;
    int   arg0;

    if(besARGNR<1) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>1) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_getcurpos(arg0);

besEND

besFUNCTION (__j_scriba_setcurpos)
    VARIABLE ptr;
    int   arg0;
    int   arg1;

    if(besARGNR<2) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>2) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_setcurpos(arg0,arg1);

besEND

besFUNCTION (__j_scriba_setechochar)
    VARIABLE ptr;
    int   arg0;
    char  arg1;

    if(besARGNR<2) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>2) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = STRINGVALUE(ptr)[0];

    besRETURNVALUE = NULL;
    japi_setechochar(arg0,arg1);

besEND

besFUNCTION (__j_scriba_seteditable)
    VARIABLE ptr;
    int   arg0;
    int   arg1;

    if(besARGNR<2) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>2) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_seteditable(arg0,arg1);

besEND

besFUNCTION (__j_scriba_setshortcut)
    VARIABLE ptr;
    int   arg0;
    char  arg1;

    if(besARGNR<2) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>2) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = STRINGVALUE(ptr)[0];

    besRETURNVALUE = NULL;
    japi_setshortcut(arg0,arg1);

besEND

besFUNCTION (__j_scriba_quit)

    if(besARGNR<0) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>0) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    besRETURNVALUE = NULL;
    japi_quit();

besEND

besFUNCTION (__j_scriba_kill)

    if(besARGNR<0) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>0) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    besRETURNVALUE = NULL;
    japi_kill();

besEND

besFUNCTION (__j_scriba_setsize)
    VARIABLE ptr;
    int   arg0;
    int   arg1;
    int   arg2;

    if(besARGNR<3) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>3) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(3);
    besDEREFERENCE(ptr);
    arg2 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_setsize(arg0,arg1,arg2);

besEND

besFUNCTION (__j_scriba_getaction)

    if(besARGNR<0) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>0) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_getaction();

besEND

besFUNCTION (__j_scriba_nextaction)

    if(besARGNR<0) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>0) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_nextaction();

besEND

besFUNCTION (__j_scriba_show)
    VARIABLE ptr;
    int   arg0;

    if(besARGNR<1) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>1) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_show(arg0);

besEND

besFUNCTION (__j_scriba_showpopup)
    VARIABLE ptr;
    int   arg0;
    int   arg1;
    int   arg2;

    if(besARGNR<3) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>3) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(3);
    besDEREFERENCE(ptr);
    arg2 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_showpopup(arg0,arg1,arg2);

besEND

besFUNCTION (__j_scriba_add)
    VARIABLE ptr;
    int   arg0;
    int   arg1;

    if(besARGNR<2) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>2) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_add(arg0,arg1);

besEND

besFUNCTION (__j_scriba_release)
    VARIABLE ptr;
    int   arg0;

    if(besARGNR<1) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>1) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_release(arg0);

besEND

besFUNCTION (__j_scriba_releaseall)
    VARIABLE ptr;
    int   arg0;

    if(besARGNR<1) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>1) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_releaseall(arg0);

besEND

besFUNCTION (__j_scriba_hide)
    VARIABLE ptr;
    int   arg0;

    if(besARGNR<1) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>1) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_hide(arg0);

besEND

besFUNCTION (__j_scriba_dispose)
    VARIABLE ptr;
    int   arg0;

    if(besARGNR<1) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>1) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_dispose(arg0);

besEND

besFUNCTION (__j_scriba_setpos)
    VARIABLE ptr;
    int   arg0;
    int   arg1;
    int   arg2;

    if(besARGNR<3) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>3) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(3);
    besDEREFERENCE(ptr);
    arg2 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_setpos(arg0,arg1,arg2);

besEND

besFUNCTION (__j_scriba_getviewportheight)
    VARIABLE ptr;
    int   arg0;

    if(besARGNR<1) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>1) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_getviewportheight(arg0);

besEND

besFUNCTION (__j_scriba_getviewportwidth)
    VARIABLE ptr;
    int   arg0;

    if(besARGNR<1) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>1) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_getviewportwidth(arg0);

besEND

besFUNCTION (__j_scriba_getxpos)
    VARIABLE ptr;
    int   arg0;

    if(besARGNR<1) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>1) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_getxpos(arg0);

besEND

besFUNCTION (__j_scriba_getypos)
    VARIABLE ptr;
    int   arg0;

    if(besARGNR<1) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>1) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_getypos(arg0);

besEND

besFUNCTION (__j_scriba_getpos)
    VARIABLE ptr;
    int   arg0;
    int*  arg1;
    int*  arg2;

    if(besARGNR<3) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>3) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));



    besRETURNVALUE = NULL;
    japi_getpos(arg0,arg1,arg2);

besEND

besFUNCTION (__j_scriba_getparentid)
    VARIABLE ptr;
    int   arg0;

    if(besARGNR<1) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>1) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_getparentid(arg0);

besEND

besFUNCTION (__j_scriba_setfocus)
    VARIABLE ptr;
    int   arg0;

    if(besARGNR<1) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>1) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_setfocus(arg0);

besEND

besFUNCTION (__j_scriba_hasfocus)
    VARIABLE ptr;
    int   arg0;

    if(besARGNR<1) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>1) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_hasfocus(arg0);

besEND

besFUNCTION (__j_scriba_getstringwidth)
    VARIABLE ptr;
    int   arg0;
    char* arg1;

    if(besARGNR<2) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>2) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = besCONVERT2ZCHAR(besCONVERT2STRING(ptr),arg1);

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_getstringwidth(arg0,arg1);

    besFREE(arg1);
besEND

besFUNCTION (__j_scriba_getfontheight)
    VARIABLE ptr;
    int   arg0;

    if(besARGNR<1) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>1) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_getfontheight(arg0);

besEND

besFUNCTION (__j_scriba_getfontascent)
    VARIABLE ptr;
    int   arg0;

    if(besARGNR<1) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>1) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_getfontascent(arg0);

besEND

besFUNCTION (__j_scriba_keylistener)
    VARIABLE ptr;
    int   arg0;

    if(besARGNR<1) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>1) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_keylistener(arg0);

besEND

besFUNCTION (__j_scriba_getkeycode)
    VARIABLE ptr;
    int   arg0;

    if(besARGNR<1) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>1) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_getkeycode(arg0);

besEND

besFUNCTION (__j_scriba_getkeychar)
    VARIABLE ptr;
    int   arg0;

    if(besARGNR<1) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>1) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_getkeychar(arg0);

besEND

besFUNCTION (__j_scriba_mouselistener)
    VARIABLE ptr;
    int   arg0;
    int   arg1;

    if(besARGNR<2) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>2) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_mouselistener(arg0,arg1);

besEND

besFUNCTION (__j_scriba_getmousex)
    VARIABLE ptr;
    int   arg0;

    if(besARGNR<1) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>1) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_getmousex(arg0);

besEND

besFUNCTION (__j_scriba_getmousey)
    VARIABLE ptr;
    int   arg0;

    if(besARGNR<1) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>1) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_getmousey(arg0);

besEND

besFUNCTION (__j_scriba_getmousepos)
    VARIABLE ptr;
    int   arg0;
    int*  arg1;
    int*  arg2;

    if(besARGNR<3) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>3) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));



    besRETURNVALUE = NULL;
    japi_getmousepos(arg0,arg1,arg2);

besEND

besFUNCTION (__j_scriba_getmousebutton)
    VARIABLE ptr;
    int   arg0;

    if(besARGNR<1) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>1) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_getmousebutton(arg0);

besEND

besFUNCTION (__j_scriba_focuslistener)
    VARIABLE ptr;
    int   arg0;

    if(besARGNR<1) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>1) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_focuslistener(arg0);

besEND

besFUNCTION (__j_scriba_componentlistener)
    VARIABLE ptr;
    int   arg0;
    int   arg1;

    if(besARGNR<2) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>2) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_componentlistener(arg0,arg1);

besEND

besFUNCTION (__j_scriba_windowlistener)
    VARIABLE ptr;
    int   arg0;
    int   arg1;

    if(besARGNR<2) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>2) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_windowlistener(arg0,arg1);

besEND

besFUNCTION (__j_scriba_setflowlayout)
    VARIABLE ptr;
    int   arg0;
    int   arg1;

    if(besARGNR<2) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>2) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_setflowlayout(arg0,arg1);

besEND

besFUNCTION (__j_scriba_setborderlayout)
    VARIABLE ptr;
    int   arg0;

    if(besARGNR<1) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>1) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_setborderlayout(arg0);

besEND

besFUNCTION (__j_scriba_setgridlayout)
    VARIABLE ptr;
    int   arg0;
    int   arg1;
    int   arg2;

    if(besARGNR<3) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>3) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(3);
    besDEREFERENCE(ptr);
    arg2 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_setgridlayout(arg0,arg1,arg2);

besEND

besFUNCTION (__j_scriba_setfixlayout)
    VARIABLE ptr;
    int   arg0;

    if(besARGNR<1) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>1) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_setfixlayout(arg0);

besEND

besFUNCTION (__j_scriba_setnolayout)
    VARIABLE ptr;
    int   arg0;

    if(besARGNR<1) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>1) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_setnolayout(arg0);

besEND

besFUNCTION (__j_scriba_setborderpos)
    VARIABLE ptr;
    int   arg0;
    int   arg1;

    if(besARGNR<2) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>2) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_setborderpos(arg0,arg1);

besEND

besFUNCTION (__j_scriba_sethgap)
    VARIABLE ptr;
    int   arg0;
    int   arg1;

    if(besARGNR<2) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>2) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_sethgap(arg0,arg1);

besEND

besFUNCTION (__j_scriba_setvgap)
    VARIABLE ptr;
    int   arg0;
    int   arg1;

    if(besARGNR<2) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>2) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_setvgap(arg0,arg1);

besEND

besFUNCTION (__j_scriba_setinsets)
    VARIABLE ptr;
    int   arg0;
    int   arg1;
    int   arg2;
    int   arg3;
    int   arg4;

    if(besARGNR<5) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>5) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(3);
    besDEREFERENCE(ptr);
    arg2 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(4);
    besDEREFERENCE(ptr);
    arg3 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(5);
    besDEREFERENCE(ptr);
    arg4 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_setinsets(arg0,arg1,arg2,arg3,arg4);

besEND

besFUNCTION (__j_scriba_setalign)
    VARIABLE ptr;
    int   arg0;
    int   arg1;

    if(besARGNR<2) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>2) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_setalign(arg0,arg1);

besEND

besFUNCTION (__j_scriba_setflowfill)
    VARIABLE ptr;
    int   arg0;
    int   arg1;

    if(besARGNR<2) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>2) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_setflowfill(arg0,arg1);

besEND

besFUNCTION (__j_scriba_translate)
    VARIABLE ptr;
    int   arg0;
    int   arg1;
    int   arg2;

    if(besARGNR<3) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>3) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(3);
    besDEREFERENCE(ptr);
    arg2 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_translate(arg0,arg1,arg2);

besEND

besFUNCTION (__j_scriba_cliprect)
    VARIABLE ptr;
    int   arg0;
    int   arg1;
    int   arg2;
    int   arg3;
    int   arg4;

    if(besARGNR<5) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>5) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(3);
    besDEREFERENCE(ptr);
    arg2 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(4);
    besDEREFERENCE(ptr);
    arg3 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(5);
    besDEREFERENCE(ptr);
    arg4 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_cliprect(arg0,arg1,arg2,arg3,arg4);

besEND

besFUNCTION (__j_scriba_drawrect)
    VARIABLE ptr;
    int   arg0;
    int   arg1;
    int   arg2;
    int   arg3;
    int   arg4;

    if(besARGNR<5) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>5) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(3);
    besDEREFERENCE(ptr);
    arg2 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(4);
    besDEREFERENCE(ptr);
    arg3 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(5);
    besDEREFERENCE(ptr);
    arg4 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_drawrect(arg0,arg1,arg2,arg3,arg4);

besEND

besFUNCTION (__j_scriba_fillrect)
    VARIABLE ptr;
    int   arg0;
    int   arg1;
    int   arg2;
    int   arg3;
    int   arg4;

    if(besARGNR<5) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>5) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(3);
    besDEREFERENCE(ptr);
    arg2 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(4);
    besDEREFERENCE(ptr);
    arg3 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(5);
    besDEREFERENCE(ptr);
    arg4 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_fillrect(arg0,arg1,arg2,arg3,arg4);

besEND

besFUNCTION (__j_scriba_drawroundrect)
    VARIABLE ptr;
    int   arg0;
    int   arg1;
    int   arg2;
    int   arg3;
    int   arg4;
    int   arg5;
    int   arg6;

    if(besARGNR<7) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>7) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(3);
    besDEREFERENCE(ptr);
    arg2 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(4);
    besDEREFERENCE(ptr);
    arg3 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(5);
    besDEREFERENCE(ptr);
    arg4 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(6);
    besDEREFERENCE(ptr);
    arg5 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(7);
    besDEREFERENCE(ptr);
    arg6 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_drawroundrect(arg0,arg1,arg2,arg3,arg4,arg5,arg6);

besEND

besFUNCTION (__j_scriba_fillroundrect)
    VARIABLE ptr;
    int   arg0;
    int   arg1;
    int   arg2;
    int   arg3;
    int   arg4;
    int   arg5;
    int   arg6;

    if(besARGNR<7) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>7) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(3);
    besDEREFERENCE(ptr);
    arg2 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(4);
    besDEREFERENCE(ptr);
    arg3 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(5);
    besDEREFERENCE(ptr);
    arg4 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(6);
    besDEREFERENCE(ptr);
    arg5 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(7);
    besDEREFERENCE(ptr);
    arg6 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_fillroundrect(arg0,arg1,arg2,arg3,arg4,arg5,arg6);

besEND

besFUNCTION (__j_scriba_drawoval)
    VARIABLE ptr;
    int   arg0;
    int   arg1;
    int   arg2;
    int   arg3;
    int   arg4;

    if(besARGNR<5) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>5) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(3);
    besDEREFERENCE(ptr);
    arg2 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(4);
    besDEREFERENCE(ptr);
    arg3 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(5);
    besDEREFERENCE(ptr);
    arg4 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_drawoval(arg0,arg1,arg2,arg3,arg4);

besEND

besFUNCTION (__j_scriba_filloval)
    VARIABLE ptr;
    int   arg0;
    int   arg1;
    int   arg2;
    int   arg3;
    int   arg4;

    if(besARGNR<5) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>5) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(3);
    besDEREFERENCE(ptr);
    arg2 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(4);
    besDEREFERENCE(ptr);
    arg3 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(5);
    besDEREFERENCE(ptr);
    arg4 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_filloval(arg0,arg1,arg2,arg3,arg4);

besEND

besFUNCTION (__j_scriba_drawcircle)
    VARIABLE ptr;
    int   arg0;
    int   arg1;
    int   arg2;
    int   arg3;

    if(besARGNR<4) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>4) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(3);
    besDEREFERENCE(ptr);
    arg2 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(4);
    besDEREFERENCE(ptr);
    arg3 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_drawcircle(arg0,arg1,arg2,arg3);

besEND

besFUNCTION (__j_scriba_fillcircle)
    VARIABLE ptr;
    int   arg0;
    int   arg1;
    int   arg2;
    int   arg3;

    if(besARGNR<4) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>4) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(3);
    besDEREFERENCE(ptr);
    arg2 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(4);
    besDEREFERENCE(ptr);
    arg3 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_fillcircle(arg0,arg1,arg2,arg3);

besEND

besFUNCTION (__j_scriba_drawarc)
    VARIABLE ptr;
    int   arg0;
    int   arg1;
    int   arg2;
    int   arg3;
    int   arg4;
    int   arg5;
    int   arg6;

    if(besARGNR<7) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>7) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(3);
    besDEREFERENCE(ptr);
    arg2 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(4);
    besDEREFERENCE(ptr);
    arg3 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(5);
    besDEREFERENCE(ptr);
    arg4 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(6);
    besDEREFERENCE(ptr);
    arg5 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(7);
    besDEREFERENCE(ptr);
    arg6 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_drawarc(arg0,arg1,arg2,arg3,arg4,arg5,arg6);

besEND

besFUNCTION (__j_scriba_fillarc)
    VARIABLE ptr;
    int   arg0;
    int   arg1;
    int   arg2;
    int   arg3;
    int   arg4;
    int   arg5;
    int   arg6;

    if(besARGNR<7) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>7) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(3);
    besDEREFERENCE(ptr);
    arg2 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(4);
    besDEREFERENCE(ptr);
    arg3 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(5);
    besDEREFERENCE(ptr);
    arg4 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(6);
    besDEREFERENCE(ptr);
    arg5 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(7);
    besDEREFERENCE(ptr);
    arg6 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_fillarc(arg0,arg1,arg2,arg3,arg4,arg5,arg6);

besEND

besFUNCTION (__j_scriba_drawline)
    VARIABLE ptr;
    int   arg0;
    int   arg1;
    int   arg2;
    int   arg3;
    int   arg4;

    if(besARGNR<5) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>5) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(3);
    besDEREFERENCE(ptr);
    arg2 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(4);
    besDEREFERENCE(ptr);
    arg3 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(5);
    besDEREFERENCE(ptr);
    arg4 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_drawline(arg0,arg1,arg2,arg3,arg4);

besEND

besFUNCTION (__j_scriba_drawpolyline)
    VARIABLE ptr;
    int   arg0;
    int   arg1;
    int*  arg2;
    int*  arg3;

    if(besARGNR<4) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>4) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(3);
    besDEREFERENCE(ptr);
    if((arg2=(int*)malloc((1+ARRAYHIGH(ptr)-ARRAYLOW(ptr)) * sizeof(int)))==NULL) return COMMAND_ERROR_MEMORY_LOW;
    {int i; for(i=0;i<=ARRAYHIGH(ptr)-ARRAYLOW(ptr);i++) arg2[i]=LONGVALUE(ARRAYVALUE(ptr,i+ARRAYLOW(ptr)));}

    ptr = besARGUMENT(4);
    besDEREFERENCE(ptr);
    if((arg3=(int*)malloc((1+ARRAYHIGH(ptr)-ARRAYLOW(ptr)) * sizeof(int)))==NULL) return COMMAND_ERROR_MEMORY_LOW;
    {int i; for(i=0;i<=ARRAYHIGH(ptr)-ARRAYLOW(ptr);i++) arg3[i]=LONGVALUE(ARRAYVALUE(ptr,i+ARRAYLOW(ptr)));}

    besRETURNVALUE = NULL;
    japi_drawpolyline(arg0,arg1,arg2,arg3);

    free(arg2);
    free(arg3);
besEND

besFUNCTION (__j_scriba_drawpolygon)
    VARIABLE ptr;
    int   arg0;
    int   arg1;
    int*  arg2;
    int*  arg3;

    if(besARGNR<4) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>4) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(3);
    besDEREFERENCE(ptr);
    if((arg2=(int*)malloc((1+ARRAYHIGH(ptr)-ARRAYLOW(ptr)) * sizeof(int)))==NULL) return COMMAND_ERROR_MEMORY_LOW;
    {int i; for(i=0;i<=ARRAYHIGH(ptr)-ARRAYLOW(ptr);i++) arg2[i]=LONGVALUE(ARRAYVALUE(ptr,i+ARRAYLOW(ptr)));}

    ptr = besARGUMENT(4);
    besDEREFERENCE(ptr);
    if((arg3=(int*)malloc((1+ARRAYHIGH(ptr)-ARRAYLOW(ptr)) * sizeof(int)))==NULL) return COMMAND_ERROR_MEMORY_LOW;
    {int i; for(i=0;i<=ARRAYHIGH(ptr)-ARRAYLOW(ptr);i++) arg3[i]=LONGVALUE(ARRAYVALUE(ptr,i+ARRAYLOW(ptr)));}

    besRETURNVALUE = NULL;
    japi_drawpolygon(arg0,arg1,arg2,arg3);

    free(arg2);
    free(arg3);
besEND

besFUNCTION (__j_scriba_fillpolygon)
    VARIABLE ptr;
    int   arg0;
    int   arg1;
    int*  arg2;
    int*  arg3;

    if(besARGNR<4) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>4) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(3);
    besDEREFERENCE(ptr);
    if((arg2=(int*)malloc((1+ARRAYHIGH(ptr)-ARRAYLOW(ptr)) * sizeof(int)))==NULL) return COMMAND_ERROR_MEMORY_LOW;
    {int i; for(i=0;i<=ARRAYHIGH(ptr)-ARRAYLOW(ptr);i++) arg2[i]=LONGVALUE(ARRAYVALUE(ptr,i+ARRAYLOW(ptr)));}

    ptr = besARGUMENT(4);
    besDEREFERENCE(ptr);
    if((arg3=(int*)malloc((1+ARRAYHIGH(ptr)-ARRAYLOW(ptr)) * sizeof(int)))==NULL) return COMMAND_ERROR_MEMORY_LOW;
    {int i; for(i=0;i<=ARRAYHIGH(ptr)-ARRAYLOW(ptr);i++) arg3[i]=LONGVALUE(ARRAYVALUE(ptr,i+ARRAYLOW(ptr)));}

    besRETURNVALUE = NULL;
    japi_fillpolygon(arg0,arg1,arg2,arg3);

    free(arg2);
    free(arg3);
besEND

besFUNCTION (__j_scriba_drawpixel)
    VARIABLE ptr;
    int   arg0;
    int   arg1;
    int   arg2;

    if(besARGNR<3) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>3) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(3);
    besDEREFERENCE(ptr);
    arg2 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_drawpixel(arg0,arg1,arg2);

besEND

besFUNCTION (__j_scriba_drawstring)
    VARIABLE ptr;
    int   arg0;
    int   arg1;
    int   arg2;
    char* arg3;

    if(besARGNR<4) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>4) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(3);
    besDEREFERENCE(ptr);
    arg2 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(4);
    besDEREFERENCE(ptr);
    arg3 = besCONVERT2ZCHAR(besCONVERT2STRING(ptr),arg3);

    besRETURNVALUE = NULL;
    japi_drawstring(arg0,arg1,arg2,arg3);

    besFREE(arg3);
besEND

besFUNCTION (__j_scriba_setxor)
    VARIABLE ptr;
    int   arg0;
    int   arg1;

    if(besARGNR<2) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>2) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_setxor(arg0,arg1);

besEND

besFUNCTION (__j_scriba_getimage)
    VARIABLE ptr;
    int   arg0;

    if(besARGNR<1) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>1) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_getimage(arg0);

besEND

besFUNCTION (__j_scriba_getimagesource)
    VARIABLE ptr;
    int   arg0;
    int   arg1;
    int   arg2;
    int   arg3;
    int   arg4;
    int*  arg5=NULL;
    LEFTVALUE  ptr5;
    int*  arg6=NULL;
    LEFTVALUE  ptr6;
    int*  arg7=NULL;
    LEFTVALUE  ptr7;
    int i,len,__refcount_;

    if(besARGNR<8) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>8) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(3);
    besDEREFERENCE(ptr);
    arg2 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(4);
    besDEREFERENCE(ptr);
    arg3 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(5);
    besDEREFERENCE(ptr);
    arg4 = LONGVALUE(besCONVERT2LONG(ptr));

    besLEFTVALUE(besARGUMENT(6),ptr5);
    if(ptr5==NULL) return(COMMAND_ERROR_ARGUMENT_TYPE);
    besRELEASE(*ptr5);
    

    besLEFTVALUE(besARGUMENT(7),ptr6);
    if(ptr6==NULL) return(COMMAND_ERROR_ARGUMENT_TYPE);
    besRELEASE(*ptr6);
    

    besLEFTVALUE(besARGUMENT(8),ptr7);
    if(ptr7==NULL) return(COMMAND_ERROR_ARGUMENT_TYPE);
    besRELEASE(*ptr7);
    

    besRETURNVALUE = NULL;
    len=__scriba_getimagesource(arg0,arg1,arg2,arg3,arg4,&arg5,&arg6,&arg7);

    if((*ptr5=besNEWARRAY(0,len-1))==NULL) return COMMAND_ERROR_MEMORY_LOW;
    for(i=0;i<len;i++)
    {
        if((ARRAYVALUE(*ptr5,i)=besNEWLONG)==NULL) return COMMAND_ERROR_MEMORY_LOW;
        LONGVALUE(ARRAYVALUE(*ptr5,i))=arg5[i];
    }
    free(arg5);

    if((*ptr6=besNEWARRAY(0,len-1))==NULL) return COMMAND_ERROR_MEMORY_LOW;
    for(i=0;i<len;i++)
    {
        if((ARRAYVALUE(*ptr6,i)=besNEWLONG)==NULL) return COMMAND_ERROR_MEMORY_LOW;
        LONGVALUE(ARRAYVALUE(*ptr6,i))=arg6[i];
    }
    free(arg6);

    if((*ptr7=besNEWARRAY(0,len-1))==NULL) return COMMAND_ERROR_MEMORY_LOW;
    for(i=0;i<len;i++)
    {
        if((ARRAYVALUE(*ptr7,i)=besNEWLONG)==NULL) return COMMAND_ERROR_MEMORY_LOW;
        LONGVALUE(ARRAYVALUE(*ptr7,i))=arg7[i];
    }
    free(arg7);

besEND

besFUNCTION (__j_scriba_drawimagesource)
    VARIABLE ptr;
    int   arg0;
    int   arg1;
    int   arg2;
    int   arg3;
    int   arg4;
    int*  arg5;
    int*  arg6;
    int*  arg7;

    if(besARGNR<8) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>8) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(3);
    besDEREFERENCE(ptr);
    arg2 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(4);
    besDEREFERENCE(ptr);
    arg3 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(5);
    besDEREFERENCE(ptr);
    arg4 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(6);
    besDEREFERENCE(ptr);
    if((arg5=(int*)malloc((1+ARRAYHIGH(ptr)-ARRAYLOW(ptr)) * sizeof(int)))==NULL) return COMMAND_ERROR_MEMORY_LOW;
    {int i; for(i=0;i<=ARRAYHIGH(ptr)-ARRAYLOW(ptr);i++) arg5[i]=LONGVALUE(ARRAYVALUE(ptr,i+ARRAYLOW(ptr)));}

    ptr = besARGUMENT(7);
    besDEREFERENCE(ptr);
    if((arg6=(int*)malloc((1+ARRAYHIGH(ptr)-ARRAYLOW(ptr)) * sizeof(int)))==NULL) return COMMAND_ERROR_MEMORY_LOW;
    {int i; for(i=0;i<=ARRAYHIGH(ptr)-ARRAYLOW(ptr);i++) arg6[i]=LONGVALUE(ARRAYVALUE(ptr,i+ARRAYLOW(ptr)));}

    ptr = besARGUMENT(8);
    besDEREFERENCE(ptr);
    if((arg7=(int*)malloc((1+ARRAYHIGH(ptr)-ARRAYLOW(ptr)) * sizeof(int)))==NULL) return COMMAND_ERROR_MEMORY_LOW;
    {int i; for(i=0;i<=ARRAYHIGH(ptr)-ARRAYLOW(ptr);i++) arg7[i]=LONGVALUE(ARRAYVALUE(ptr,i+ARRAYLOW(ptr)));}

    besRETURNVALUE = NULL;
    japi_drawimagesource(arg0,arg1,arg2,arg3,arg4,arg5,arg6,arg7);

    free(arg5);
    free(arg6);
    free(arg7);
besEND

besFUNCTION (__j_scriba_getscaledimage)
    VARIABLE ptr;
    int   arg0;
    int   arg1;
    int   arg2;
    int   arg3;
    int   arg4;
    int   arg5;
    int   arg6;

    if(besARGNR<7) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>7) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(3);
    besDEREFERENCE(ptr);
    arg2 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(4);
    besDEREFERENCE(ptr);
    arg3 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(5);
    besDEREFERENCE(ptr);
    arg4 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(6);
    besDEREFERENCE(ptr);
    arg5 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(7);
    besDEREFERENCE(ptr);
    arg6 = LONGVALUE(besCONVERT2LONG(ptr));

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_getscaledimage(arg0,arg1,arg2,arg3,arg4,arg5,arg6);

besEND

besFUNCTION (__j_scriba_drawimage)
    VARIABLE ptr;
    int   arg0;
    int   arg1;
    int   arg2;
    int   arg3;

    if(besARGNR<4) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>4) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(3);
    besDEREFERENCE(ptr);
    arg2 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(4);
    besDEREFERENCE(ptr);
    arg3 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_drawimage(arg0,arg1,arg2,arg3);

besEND

besFUNCTION (__j_scriba_drawscaledimage)
    VARIABLE ptr;
    int   arg0;
    int   arg1;
    int   arg2;
    int   arg3;
    int   arg4;
    int   arg5;
    int   arg6;
    int   arg7;
    int   arg8;
    int   arg9;

    if(besARGNR<10) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>10) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(3);
    besDEREFERENCE(ptr);
    arg2 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(4);
    besDEREFERENCE(ptr);
    arg3 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(5);
    besDEREFERENCE(ptr);
    arg4 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(6);
    besDEREFERENCE(ptr);
    arg5 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(7);
    besDEREFERENCE(ptr);
    arg6 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(8);
    besDEREFERENCE(ptr);
    arg7 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(9);
    besDEREFERENCE(ptr);
    arg8 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(10);
    besDEREFERENCE(ptr);
    arg9 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_drawscaledimage(arg0,arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8,arg9);

besEND

besFUNCTION (__j_scriba_setcolor)
    VARIABLE ptr;
    int   arg0;
    int   arg1;
    int   arg2;
    int   arg3;

    if(besARGNR<4) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>4) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(3);
    besDEREFERENCE(ptr);
    arg2 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(4);
    besDEREFERENCE(ptr);
    arg3 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_setcolor(arg0,arg1,arg2,arg3);

besEND

besFUNCTION (__j_scriba_setcolorbg)
    VARIABLE ptr;
    int   arg0;
    int   arg1;
    int   arg2;
    int   arg3;

    if(besARGNR<4) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>4) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(3);
    besDEREFERENCE(ptr);
    arg2 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(4);
    besDEREFERENCE(ptr);
    arg3 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_setcolorbg(arg0,arg1,arg2,arg3);

besEND

besFUNCTION (__j_scriba_setnamedcolor)
    VARIABLE ptr;
    int   arg0;
    int   arg1;

    if(besARGNR<2) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>2) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_setnamedcolor(arg0,arg1);

besEND

besFUNCTION (__j_scriba_setnamedcolorbg)
    VARIABLE ptr;
    int   arg0;
    int   arg1;

    if(besARGNR<2) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>2) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_setnamedcolorbg(arg0,arg1);

besEND

besFUNCTION (__j_scriba_loadimage)
    VARIABLE ptr;
    char* arg0;

    if(besARGNR<1) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>1) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = besCONVERT2ZCHAR(besCONVERT2STRING(ptr),arg0);

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_loadimage(arg0);

    besFREE(arg0);
besEND

besFUNCTION (__j_scriba_saveimage)
    VARIABLE ptr;
    int   arg0;
    char* arg1;
    int   arg2;

    if(besARGNR<3) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>3) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    ptr = besARGUMENT(2);
    besDEREFERENCE(ptr);
    arg1 = besCONVERT2ZCHAR(besCONVERT2STRING(ptr),arg1);

    ptr = besARGUMENT(3);
    besDEREFERENCE(ptr);
    arg2 = LONGVALUE(besCONVERT2LONG(ptr));

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_saveimage(arg0,arg1,arg2);

    besFREE(arg1);
besEND

besFUNCTION (__j_scriba_sync)

    if(besARGNR<0) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>0) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    besRETURNVALUE = NULL;
    japi_sync();

besEND

besFUNCTION (__j_scriba_beep)

    if(besARGNR<0) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>0) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    besRETURNVALUE = NULL;
    japi_beep();

besEND

besFUNCTION (__j_scriba_random)

    if(besARGNR<0) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>0) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    besALLOC_RETURN_LONG;
    LONGVALUE(besRETURNVALUE) = japi_random();

besEND

besFUNCTION (__j_scriba_sleep)
    VARIABLE ptr;
    int   arg0;

    if(besARGNR<1) return EX_ERROR_TOO_FEW_ARGUMENTS; 
    if(besARGNR>1) return EX_ERROR_TOO_MANY_ARGUMENTS; 

    ptr = besARGUMENT(1);
    besDEREFERENCE(ptr);
    arg0 = LONGVALUE(besCONVERT2LONG(ptr));

    besRETURNVALUE = NULL;
    japi_sleep(arg0);

besEND

