' """
FILE: japi.bas

This is the BASIC import file for the module japi.

This file was generated by headerer.pl from the file interface.c
Do not edit this file, rather edit the file interface.c and use
headerer.pl to regenerate this file.
"""

module japi

' FUNCTION DECLARATIONS 
declare sub     ::functionname alias "functionname" lib "japi"

end module
